import type { Anime } from './types';

export const mockGenres = [
  "Action", "Adventure", "Comedy", "Drama", "Fantasy", "Horror", "Mecha", "Music", "Mystery", "Psychological", "Romance", "Sci-Fi", "Slice of Life", "Sports", "Supernatural", "Thriller"
];

export const mockAnime: Anime[] = [
  {
    id: '1',
    title: 'Cyber Ronin',
    poster: 'https://picsum.photos/400/600?random=1',
    description: 'In a neon-drenched future, a lone cyborg samurai battles a corrupt megacorporation to reclaim his lost memories and honor.',
    rating: 9.2,
    genres: ['Action', 'Sci-Fi', 'Mecha'],
    type: 'TV',
    status: 'Airing',
    addedDate: '2024-07-20T10:00:00Z',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `e${i + 1}`,
      title: `Episode ${i + 1}: Awakening`,
      episodeNumber: i + 1,
      thumbnail: `https://picsum.photos/320/180?random=${10 + i}`,
      duration: 24,
    })),
  },
  {
    id: '2',
    title: 'Forest of Whispers',
    poster: 'https://picsum.photos/400/600?random=2',
    description: 'A young girl discovers she can communicate with ancient spirits of the forest. Together, they must protect their home from a creeping darkness.',
    rating: 8.8,
    genres: ['Fantasy', 'Supernatural', 'Slice of Life'],
    type: 'Movie',
    status: 'Completed',
    addedDate: '2024-07-18T10:00:00Z',
    episodes: [{
      id: 'e1',
      title: 'The Full Movie',
      episodeNumber: 1,
      thumbnail: `https://picsum.photos/320/180?random=20`,
      duration: 120,
    }],
  },
  {
    id: '3',
    title: 'Galactic Drifters',
    poster: 'https://picsum.photos/400/600?random=3',
    description: 'The misfit crew of the starship "Stardust" takes on odd jobs across the galaxy, usually with hilarious and disastrous results.',
    rating: 8.5,
    genres: ['Comedy', 'Sci-Fi', 'Adventure'],
    type: 'TV',
    status: 'Airing',
    addedDate: '2024-07-15T10:00:00Z',
    episodes: Array.from({ length: 24 }, (_, i) => ({
      id: `e${i + 1}`,
      title: `Job ${i + 1}: The Space Delivery`,
      episodeNumber: i + 1,
      thumbnail: `https://picsum.photos/320/180?random=${30 + i}`,
      duration: 23,
    })),
  },
  {
    id: '4',
    title: 'The Last Alchemist',
    poster: 'https://picsum.photos/400/600?random=4',
    description: 'In a world where alchemy is forbidden, a brilliant young practitioner seeks the legendary Philosopher\'s Stone to save his ailing sister.',
    rating: 9.5,
    genres: ['Drama', 'Fantasy', 'Psychological'],
    type: 'Completed',
    status: 'Completed',
    addedDate: '2024-07-12T10:00:00Z',
    episodes: Array.from({ length: 51 }, (_, i) => ({
      id: `e${i + 1}`,
      title: `Chapter ${i + 1}: The Taboo`,
      episodeNumber: i + 1,
      thumbnail: `https://picsum.photos/320/180?random=${50 + i}`,
      duration: 25,
    })),
  },
  {
    id: '5',
    title: 'Tokyo Beat',
    poster: 'https://picsum.photos/400/600?random=5',
    description: 'An underground DJ and a shy ballerina form an unlikely duo, aiming to conquer Tokyo\'s competitive music and dance scene.',
    rating: 8.2,
    genres: ['Music', 'Romance', 'Slice of Life'],
    type: 'OVA',
    status: 'Completed',
    addedDate: '2024-07-10T10:00:00Z',
    episodes: Array.from({ length: 6 }, (_, i) => ({
      id: `e${i + 1}`,
      title: `Beat ${i + 1}`,
      episodeNumber: i + 1,
      thumbnail: `https://picsum.photos/320/180?random=${100 + i}`,
      duration: 22,
    })),
  },
  {
    id: '6',
    title: 'Dimension Detective',
    poster: 'https://picsum.photos/400/600?random=6',
    description: 'A cynical detective solves crimes that cross the boundaries of reality itself, aided by a partner from another dimension.',
    rating: 8.9,
    genres: ['Mystery', 'Sci-Fi', 'Thriller'],
    type: 'TV',
    status: 'Airing',
    addedDate: '2024-07-08T10:00:00Z',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `e${i + 1}`,
      title: `Case ${i + 1}: The Shift`,
      episodeNumber: i + 1,
      thumbnail: `https://picsum.photos/320/180?random=${110 + i}`,
      duration: 24,
    })),
  },
  // Add 14 more mock anime to have a good variety
  ...Array.from({ length: 14 }, (_, i) => ({
    id: `${i + 7}`,
    title: `Generic Anime Title ${i + 7}`,
    poster: `https://picsum.photos/400/600?random=${i + 7}`,
    description: 'A thrilling tale of adventure and discovery in a world much like our own, yet different.',
    rating: Number((7 + Math.random() * 2.5).toFixed(1)),
    genres: [mockGenres[i % mockGenres.length], mockGenres[(i + 3) % mockGenres.length]],
    type: (['TV', 'Movie', 'OVA', 'Special'] as const)[i % 4],
    status: (['Airing', 'Completed'] as const)[i % 2],
    addedDate: `2024-07-${10 - i > 0 ? 10-i: 1}T10:00:00Z`,
    episodes: Array.from({ length: 12 }, (v, j) => ({
      id: `e${j + 1}`,
      title: `Episode ${j + 1}`,
      episodeNumber: j + 1,
      thumbnail: `https://picsum.photos/320/180?random=${200 + i * 12 + j}`,
      duration: 24,
    })),
  }))
];
